### ISSUE TITLE
Active development? What is missing for 1.0?

### ISSUE THREAD

**Issue by minecrawler** [Download/mics#1]
I would like to use a stable mixin-module. However, I can only find the PoC by Justin Fagnani and your implementation. Instead of creating yet another module, I would like to build on top of your solution. That's why I want to know, if you still actively develop the project (and plan to continue doing so) and why your package is not v1.0: what stuff is still missing?

**Comment by Download** [comment]
Hi @minecrawler, sorry for the late response. It seems I'm not always getting the notifications in the Github control panel.

Anyway, development is still active in the sense that this code is intended to go into production.
The reasons it is still 0.x are:

* It's not yet in production
* I still have some plans to change it
* There is an upcoming issue still
* I always like to take it slow with moving to 1.0 so when I do publish the 1.0 version, I'm pretty sure I can keep it at that version for a while. I wouldn't want to send the wrong message to people about the status of this module.

That said, the module has some extensive tests on them that are run in the CB and I plan to add more tests whenever I change stuff, so I expect it to be relatively stable.

The upcoming issue is that currently this module checks whether the given argument is an ES6 class. This can be feature tested in ES6 compliant browsers, but is trickier with transpiled code. At the moment this module checks whether some babel specific transpiled code is present to detect if the argument is a transpiled ES6 class. However, Babel is currently [optimizing their output](https://github.com/babel/babel/pull/4850) with a loose mode that gives much compacter code (jay!), but that change will break this package. So I want to tackle that as well before going to 1.0.

About what's missing. Not much I think. This lib is very minimalistic, but should give you exactly the stuff needed to start using and building mixins in your project.

I do still have this dilemma. Currently mics has two functions: `mix` and `is`. The result of `is` exposes three more functions: `a`, `an` (just an alias for `a`), and `as`. My doubt is, is the fluid syntax really worth it? Maybe mics should just expose 3 functions? `mix`, `is` and `as` ?

What do you think?

Also, can you tell me about your ideas what you would build on top of it? I would really like it if you would want to collaborate with me on this lib.

**Comment by minecrawler** [comment]
Hi @Download , wow, that's a very detailed response, thank you a lot. I can understand if you want to take it slow with releasing version 1, so that it remains stable.

As for the Babelized-code dilemma, I do not think that it will affect me, as I mostly build Node.JS and Cordova applications, and limit the minimum versions on which my software runs. As a result, I will probably be able to use mics even though it won't work after being transpiled to <=ES5. That's an advantage for me, because I can confidently use mics while you still work on supporting that.

The point about the API, however, might be a bit problematic, since when I use mics, I do not want to change my code every time I update the lib, because for at least one of the projects, which should use mics, that would mean that I have to change 20 packages in several places.

Since I plan to use mics, I plan to collaborate with you on this lib. Only by usage, many problems and missing features can be found (which I need), so I will gladly implement them and send them upstream. However, before doing that step, I think it is important to at least decide on the API. I have no problems changing my project once or twice later on, if there are real reasons to change the API. However, how you want to style the API is entirely up to you. To answer your question, though: I don't really like fluid style. The method names tell me so little about what is going on or how I could complete the chain. I would prefer an interface like

```js
/**
 * Mix classes
 * Any class can be transformed to a mixin (by calling `.mix()`,
 * but can also be instantiated on its own
 */
class Mics {
  /**
   * Create a mixin from a class
   * Multiple classes or mixins can be mixed into the resulting mixin
   *
   * @param {MixinFactory} superclass, returns a class extending the first parameter
   * @param {...MixinFactory} mixins, return a class extending the first parameter
   * @param {function} factory
   * @return {object}
   */
  static mix(superclass, ...mixins, factory) {}

  /**
   * Check if an object was created with a certain mixin
   *
   * @param {object} obj
   * @param {class} mixin
   * @return {boolean}
   */
  static hasMixin(obj, mixin) {}

  /**
   * Check if an object can be used as if it was created with a certain mixin
   *
   * @param {object} obj
   * @param {class} mixin
   * @return {boolean}
   */
  static likeMixin(obj, mixin) {}
}

/**
 * This callback creates a class-extending class
 *
 * @callback MixinFactory
 * @param {class} superclass
 * @return {class}
 */
```

But, again, that's personal taste and you will have to decide on the actual interface. If you are not sure about it, maybe open an issue others can track and close it once you feel confident with the interface. You could also discuss different approaches there ;)

What would I build on top of it? Among commercial products, I am working on an [open-source application-host](https://github.com/Skellods-Network/SHPS4Node), which provides certain basic features, but focuses on security, speed and scalability. I am currently in a major redesign-phase (for SHPS v5 X), in which I would like to use mixins for [various purposes](https://github.com/Skellods-Network/SHPS4Node/issues/92), like [sandbox-features](https://github.com/Skellods-Network/SHPS4Node-sandbox/issues/2) or preparing a central foundation for the separate modules. I think, mixins are a lot more stable than testing available methods, hence the right way to go.

**Comment by Download** [comment]
Ah yes I think I see where you want to use it. As a way to implement features to compose modules/plugins with, right? That would be awesome!

SHPS looks very interesting. It's sorta sad that WordPress is still the king of the hill as far as CMS' go, even though it's actually an overgrown blogging system. Would be really cool to see it get some competition.

When I did some research for WordPress alternatives a stumbled on one system that used plugins a la WordPress, but they had this really cool thing. Instead of having to download zip files, you could actually link to a GitHub repo of a plugin and it would pick it up automatically. That was an awesome feature I think. Anyway....

I understand the concerns about the API. I don't like changing them and breaking everyone. Which is why, once we go 1.0, it should be stable. Also, I'll give you a heads-up and possibly even help you upgrading if something did break,

> I don't really like fluid style.

Yes I can understand that. It sorta evolved like this from the original blog article, which uses `mix(..),with(..)`. I already decided that I think that just always using `mix(..., ..., ...)` is easier, so I probably should go all the way and do the same for `is..a`. 

I like your idea of `hasMixin` and `likeMixin` as well... But `is` does a bit more besides checking for mixins. It also works for regular classes and even some strings. E.g.

```js
is(function test(){}, 'function')  // true
```

I have been doubting about `as` especially. It is pretty clear in the context `is(subject).as(Type)`, but when it stands on it's own it's a lot less clear:

```js
as(subject, Type)
```
This looks like it might be performing a conversion or cast. I know e.g. Object Pascal actually has keyword `as` to perform checked cast... So maybe I can use `like` from your suggestion:

```js
like(subject, Type)
```

I think this is more clearly a test that returns a boolean.

What do you think about this export structure:

```js
mics {
  mix,
  is,
  like,
}
```

I think it may be very readable like this:

```js
import { mix, is, like } from 'mics'

var viewer = {              // create an object with the 
  look(){}                  // same interface as Looker 
}     
is(viewer, Looker)          // false, but 
like(viewer, Looker)        // true 
```

I like this actually. I'm a big sucker for (really) short names, but sometimes it's just not descriptive enough. I think `like` has better balance in that regard than `as`. 

I can see if I can whip out an 0.6 version with this API this weekend. You can test it a bit.

> Only by usage, many problems and missing features can be found

Exactly! right? Which is why it was 'stuck' at 0.5. Still working on other parts of my code so this did not yet get that testing and usage. But if you are also testing it we can move to 1.0 quicker.

Let me know what you think. Since, besides from myself, you would be the first serious user of this lib I very much value your input.

**Comment by minecrawler** [comment]
> SHPS looks very interesting. It's sorta sad that WordPress is still the king of the hill as far as CMS' go, even though it's actually an overgrown blogging system. Would be really cool to see it get some competition.

I do not want to compete with Wordpress, as SHPS is not a CMS. It is a lot more fundamental and meant for real web developers, although I've been planning to add an elaborate GUI (for several years now >.<). SHPS might, however, be transformed into a CMS by plugins, which are installable on top. Btw, downloading and installing plugins should work via cli `> plugin add Download/samplePlugin` from npm and github, however I first have to define certain stuff about plugins and implement the dependency-module, so that it can actually interface with the sources and packages properly.

Back to topic. As for your interface proposal, I think we agree more or less on how the functionality should be exposed. So, what's left is to consolidate the API and update the unit tests. As soon as you did that, I could set up the mixin stuff on my side and give you some feedback on the feeling and if I need different functionality and edge-cases I encounter. Well, I probably made that sound too easy.

I also think that this issue is not really the right place to discuss all those things, since I only wanted to ping you to see if I can use this lib. That question has been answered, thank you! I will close this issue and open dedicated issues for better tracking.
