### ISSUE TITLE
Remove support for type string from `is`

### ISSUE THREAD

**Issue by minecrawler** [Download/mics#22]
In the test, there are rules, like

```js
expect(is(function(){}, 'factory')).to.eq(false)
expect(is(function(x){}, 'factory')).to.eq(true)
expect(is(function(x,y){}, 'factory')).to.eq(false)
```

1. The number of parameters on a function should never give any indications about the intention of a function. The intent of a function is implementation-specific, not declaration-specific.
2. There can be factories with multiple or no arguments at all!

**Comment by Download** [comment]
Actually, mics defines what it considers to be a 'class factory':

* An arrow function
* With a single argument, which must be a class
* Which returns a class extending the given superclass

In the context of `mix`, a factory can never have more or less than exactly one argument. That is what `mix` expects.

The reason I actually test for the function length is because the tests for 'factory', 'class' and 'function' are (unfortunately) not watertight. But it is the only thing that allows the `mix` function to have it's very relaxed signature of accepting an optional superclass, optional mixins and optional factory (at least one of which must be given). So the function length check helps minimize the chances of issues. **IF** you use Babel loose optimizations **AND** you have a class with a constructor that accepts exactly one argument **AND** you are passing this class as the only argument to `mix` THEN you might get an issue where `mix` mistakes it for a factory... I have to do some testing with loose mode to see if it can be solved. If not, probably a big fat warning in the docs + some workaround for this edge case is needed.

I am not sure whether actually exposing the tests for `factory`, `class` and `function` with `is` are useful. But the code relies on those tests internally...  I could use some insight from you on that maybe,

**Comment by Download** [comment]
I have been thinking about it some more.

You provide very interesting feedback. I tend to think my docs are very clear but I am biased because I already know how it is supposed to work.

> There can be factories with multiple or no arguments at all!

You are absolutely right. Only the *class factories* that `mix` expects can have only a single argument. But factories in general.... who knows. Currently it is implicit that `is(subject, 'factory')` actually tests whether `subject` is a *class factory*.

I propose we change the string `factory` to `class-factory` to make it clear:

```js
is(subject, 'class-factory')
```

**Comment by minecrawler** [comment]
Hmm, even then, it is a bit misleading. Anyone who uses the "specs", as you named it, to learn how to use mics by example, will find that method there, cross-check with the docs, which do not have any warning about it at all, and use it. Then something will fail and they will find out that the function returns a false return value. They will file a bug report.

That's why, imho, internal stuff should not be made accessible from the outside and should not occur in the specs. I would suggest splitting `is()` into `is()` and `isExt()` (for "is_extended", alternatively `isInt()` for "is_internal", however that might be confused with "integer"), of which only `is()` is exported and `isExt()` also tests for the internal stuff.

Then, the tests could also be put into multiple files, so that we have one file for exported things and one file for internal stuff.

**Comment by Download** [comment]
Yes I see your point.
Ok let us do as you propose!  👍 
See also [Finalize API #2](https://github.com/Download/mics/issues/2)
